on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        scala:
          - "2.12.17"
          - "2.13.10"
          - "2.13.11-M1"
          - "3.2.2"
          - "3.3.0-RC3"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8
    - run: sbt "++ ${{matrix.scala}}!" test
